name: Main

on: [push]

jobs:
  TrffleHog:
    runs-on: ubuntu-latest
    name: A job to scan for secrets
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Secret Scan
        id: Truffle-Hog
        uses: JiDevOps/secret-scan@master
        with:
          include_path: 'Configuration/include_paths.txt'
          exclude_path: 'Configuration/exclude_paths.txt'
